# 线上配置文件
server:
  address: 0.0.0.0
  port: 8101
  servlet:
    context-path: /api
    session:
      cookie:
#        domain: 117.72.10.108
        domain: http://woodapi.wood-yang.cn/
        max-age: 259200
spring:
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://117.72.10.108:23148/woodapi
    url: jdbc:mysql://localhost:23148/woodapi
    username: wood
    password: bB5JBj6P6iYJih65
dubbo:
  application:
    #设置应用的名称
    name: dubbo-springboot-provider
    qos-enable: true
    qos-port: 23444
  #指定使用Dubbo协议，且端口设置为-1，表示随机分配可用端口
  protocol:
    name: dubbo
    port: -1
  registry:
    #配置注册中心为Nacos
    id: nacos-registry
#    address: nacos://172.30.0.3:8848
    address: nacos://localhost:8848

mybatis-plus:
  configuration:
    # 生产环境关闭日志
    log-impl: ''
# 接口文档配置
knife4j:
  basic:
    enable: true
    username: root
    password: 123456
