# 公共配置文件
spring:
  application:
    name: woodapi-backend
  # 默认 dev 环境
  profiles:
    active: dev
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session 配置
  session:
    # todo 取消注释开启分布式 session（须先配置 Redis）
    # store-type: redis
    # 30 天过期
    timeout: 2592000
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://gz-tdsql-darrkhl7.sql.tencentcdb.com:21056/woodapi
    username: wood
    password: 20010309Npy!
  # Redis 配置
  # todo 需替换配置，然后取消注释
  redis:
    host: r-2vc8otahhn18exw8zhpd.redis.cn-chengdu.rds.aliyuncs.com
    port: 6379
    password: 20010309npy!
    database: 1
    timeout: 5000
  # Elasticsearch 配置
  # todo 需替换配置，然后取消注释
#  elasticsearch:
#    uris: http://localhost:9200
#    username: root
#    password: 123456
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
server:
  address: 0.0.0.0
#  port: 8080
  port: 8080
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）


dubbo:
  application:
    #设置应用的名称
    name: dubbo-springboot-provider
    qos-enable: true
    qos-port: 23444
    qos-accept-foreign-ip: false
  #指定使用Dubbo协议，且端口设置为-1，表示随机分配可用端口
  protocol:
    name: dubbo
    port: -1
  registry:
    #配置注册中心为Nacos
    id: nacos-registry
    address: nacos://localhost:8848
    username: nacos
    password: nacos
    parameters:
      namespace: 72274348-f2dd-4049-8f92-3609f5122748   #nacos命名空间
    group: dubbo-woodapi   #nacos分组
    file: C:\Users\24420\.dubbo\gateway
  file: C:\Users\24420\.dubbo\gateway
  config-center:
    timeout: 40000 #设置服务超时时间
    file: C:\Users\24420\.dubbo\gateway
# 接口文档配置
#knife4j:
#  enable: true
#  openapi:
#    title: "接口文档"
#    version: 1.0
#    group:
#      default:
#        api-rule: package
#        api-rule-resources:
#          - com.wood.woodapi.controller
woodapi:
  client:
    access-key: wood
    secret-key: abc
